Numpy

In [1]:
import numpy as np
print(np.__version__)

2.3.5


Aggregrate function with numpy

In [85]:
#my_list = [1,2,3,4]
#my_list = my_list * 2 without using numpy its not multiple the number instead duplicate it and make one more list kind of

array = np.array([1,2,3,4])

array = array + 2 

print(array)
print(type(array)) #we can also check the class type 

#(where d meaning is n number of dimensional )

[3 4 5 6]
<class 'numpy.ndarray'>


Multidimensional arrays and chain indexing

In [ ]:
#array = np.array("") #"this is zero dimensional array

#print(array.ndim) # this way we can also check the dimensional array

#array = np.array(["a","b","c"]) # this is 1D

#array = np.array(["[1]","[2]","[3]"]) # this is also 1D

#array = np.array([["1","2","3"]]) # this is  2D 

#array = np.array([[["1","2","3"]]]) # this is  3D 

#array = np.array([[[["1","2","3"]]]]) # this is  4D 

#print(array.shape) #it shows us a layer rows and columns

# And so on and on

array = np.array([[["a","b","c"],["d","e","f"],["g","h","i"]], 
                 [["j","k","l"],["m","n","o"],["p","q","r"]], 
                 [["s","t","u"],["v","w","x"],["y","z","9"]]])

#It knows as chain indexing

#print(array[1][0][1]) #how to element access for eg i want only "k"
print(array[1][1][0]) #how to element access for eg i want only "m"

m


Multidimensional indexing also it is faster than chain indexing

In [ ]:
array = np.array([[["a","b","c"],["d","e","f"],["g","h","i"]], 
                 [["j","k","l"],["m","n","o"],["p","q","r"]], 
                 [["s","t","u"],["v","w","x"],["y","z","9"]]])

#print(array[1,1,0])
#suppose  have to write my name with this

word = array[1,1,0] + array[0,0,0] + array[1,1,1] + array[0,0,0] + array[2,1,0]

print(word)

manav


Slicing

In [ ]:
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

#array[start:end:step]

#print(array[0]) # access first list

#print(array[1]) # access second list

#print(array[2]) # access third list

#print(array[3]) # access fourth list

#print(array[0:3]) # this will select first 3 line

#print(array[0:4:2]) # this will select only 2 line on count 2

#print(array[:,0]) # this will select only 1 column

#print(array[:,3]) # this will select only 1 column  

#print(array[:,0:3]) # this will select 3 

#print(array[0:3,0:1]) # this will select layer from 0 to 3 row and select one column with 0:1

print(array[2:3,0:1]) #this how se select only one digit with slice

[[9]]


scalar arthmetic

In [ ]:
array = np.array([1,2,3])

print(array + 1)
print(array - 2)
print(array * 2)
print(array / 2)
print(array ** 2)

[2 3 4]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]


vectorized math function

In [91]:
array = np.array([1.1,2.2,3.5])
print(np.sqrt(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.min(array))
print(np.max(array))
print(np.max(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array)) 

#exercise
radii = np.array([1,2,3])
print(np.pi * radii ** 2)

[1.04880885 1.4832397  1.87082869]
2.266666666666667
2.2
0.9809292646374774
1.1
3.5
3.5
[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]
[ 3.14159265 12.56637061 28.27433388]


element wise arthmetic

In [92]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


COMPARISON operators

In [99]:
scores = np.array([100,49,48,57,55,64,10])
scores[scores < 60] = 0
print(scores)
print(scores == 100 )
print(scores >= 100 )

[100   0   0   0   0  64   0]
[ True False False False False False False]
[ True False False False False False False]


Broadcasting
broadcasting allows numpy to perform operations on arrays
with different shapes by virtually expanding dimensions
so thw=ey match the larger array's shape

the dimensions have the same size
or
one of the dimensions has a size of 1

In [ ]:
array1 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array1.shape)
print(array1 * array2)

(4, 4)
(4, 4)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


Filtering in numpy
refers to the process of selecting elements from an array that much a given condition

In [130]:
ages = np.array([[21,18,20,19,22,23,54,10,15],
                [1,8,60,9,82,73,64,10,14]])
teenagers = ages[ages < 18]
adult = ages[ages < 18 & (ages >= 60)]
senior = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
zero = np.where(ages >=18, ages, 0)
print(zero)

[[21 18 20 19 22 23 54  0  0]
 [ 0  0 60  0 82 73 64  0  0]]


Random numbers

In [272]:
rng =np.random.default_rng(seed=1) #seed is for same result again and again
print(rng.integers(low=1,high=101, size=(3,2)))

print(np.random.uniform(low=-1, high=1, size=2))

rng = np.random.default_rng()
arrays = np.array([1,2,3,4,5])
#rng.shuffle(array)
array = rng.choice(arrays)
print(array)

[[48 52]
 [76 96]
 [ 4 15]]
[0.93968281 0.15466506]
5
